### PR TITLE
Organize file into respective asset folders and renamed some images .

### PR DESCRIPTION
**Pull request by ChinmayMhatre**
This pull request addresses issue #14 .

Here are the renamed images : 
`1`     into  `mlh-welcome` 
`23`   into  `mlh-form`
`6`     into  `chibi`

the `css, images` have been put into there respective folders and a `js` folder has been created for future use.

links in the `html` document have been updated

### CODE REVIEW

**Comment by kcoder63** [comment]
Awesome,Thank you for contributing!

**Comment by kcoder63** [comment]
Oops we need to modify the README too

**Comment by ChinmayMhatre** [comment]
> Oops we need to modify the README too

I guess I changed the links in the read me . Is there some issue?

**Comment by kcoder63** [comment]
Yeah it looks like this
Screenshot_2021-03-24-08-57-59-998_com android chrome

**Comment by ChinmayMhatre** [comment]
Oh okay .I'll create another pr for this.

**Pull request merged**
