### PR TITLE
Adding the contents for the Join page

### PR DESCRIPTION
**Pull request by kulendu**
Adding Instructions and buttons in join page (#27). 
Annotation 2021-03-25 201311
<br />
 Also adjusted the padding in the about page.

### CODE REVIEW

**Review by kcoder63 — APPROVED** [review]
Awesome! LGTM, thank you so much for giving the finishing touches. I think the site is complete for now, still open for improvements if there are any. Thanks for contributing :)

**Comment by kulendu** [comment]
Thanks a lot @kcoder63 , it was really fun working on this project. And also I think we should add some thing like the footer section, and also I think the bugs in the attached image, should be fixed. Like all the other form options are not referring to any links, so keeping them open like this will make the website look unfininshed, what say??

Annotation 2021-03-25 202454

**Comment by kulendu** [comment]
Awesome, so should I open an issue where we can discuss about the footer

**Comment by kcoder63** [comment]
Yes please ☺️

**Pull request merged**
