### PR TITLE
Added Footer to Join us page 

### LINKED ISSUE #80: Add footer for Join us page !!
As we have created the footer for about us page we can add the same for join us page  and also for home page

### PR DESCRIPTION
**Pull request by rohank2502**
Fixes #80

### CODE REVIEW

**Review by vinzvinci — CHANGES_REQUESTED** [review]
Hi can you fix this indentation?

indent

And can you make a screenshot what it looks like in the webpage after changing?

**Comment by kcoder63** [comment]
yeah it'll be better if the screenshots are provided of before and after, it'll make it easier to look at changes and merge the PR

**Comment by rohank2502** [comment]
Done @kcoder63

**Review by vinzvinci — COMMENTED** [review]
I like your work.

Take a look the changes here <a href="https://rohank2502.github.io/Eddiehub_share/join.html">https://rohank2502.github.io/Eddiehub_share/join.html</a>
 @kcoder63

**Comment by kcoder63** [comment]
yep, nice! thank you :)

**Pull request merged**
