### PR TITLE
Add a Flask Backend

### LINKED ISSUE #89: nav bar in about.html
**Describe the bug**
I was able to add nav bar in index.html and join.html but could not do it in about.html, I used the same method for both, any help would be appreciated
ab
solved

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by sudiptog81**
Added a Flask Backend, with GitHub OAuth and upload logic. Will have to rethink storage. Heroku is non persistent, a DB will get bulky. Will look at object storage. :+1: 

Closes #89 as well.

### CODE REVIEW

**Comment by sudiptog81** [comment]
I'll rebase my commits in a jiffy.

**Comment by kcoder63** [comment]
There's some conflict

**Comment by sudiptog81** [comment]
Resolved :+1:

**Comment by kcoder63** [comment]
Good to go?

**Comment by sudiptog81** [comment]
No, will add that feature soon. This is just a preparation for that.

**Pull request merged**
